#!/bin/sh
#
# description: Starts/stops the pytrain instance under Debian.
#
### BEGIN INIT INFO
# Provides:       pytrain
# Required-Start: $network $remote_fs
# Required-Stop:  $network $remote_fs
# Default-Start:  3 5
# Default-Stop:   0 1 2 6
# Description:    Starts the PyTrain controller
### END INIT INFO

# Source debian's function library.
. /lib/lsb/init-functions

# installation directory
PYTRAIN_HOME=/usr/share/pytrain

START_STOP_OPTS="--pidfile /run/pytrain"

case $1 in
	start)
		log_begin_msg "Starting pytrain..."
		PYTHONPATH=$PYTRAIN_HOME/src start-stop-daemon --start $START_STOP_OPTS --exec /usr/bin/python --background --make-pidfile -- -B $PYTRAIN_HOME/src/pytrain/Main.py 
		log_end_msg $?
		;;
	stop)
		log_begin_msg "Stopping pytrain..."
		start-stop-daemon --stop $START_STOP_OPTS
		log_end_msg $?
		;;
	restart)
		$0 stop && $0 start
		;;
	status)
		log_begin_msg "Checking for pytrain..."
		start-stop-daemon --status $START_STOP_OPTS
		log_end_msg $? 
		;;
	*)
		echo "Usage: $0 {start|stop|status|restart}"
		exit 1
esac
